import matplotlib.pyplot as plt
import pandas as pd
data=pd.read_csv("retail_sales_data.csv")
data['date']=pd.to_datetime(data['date'])
data['month']=data['date'].dt.month
monthly_sale=data.groupby('month')['sales'].sum()
plt.figure()
plt.plot(monthly_sale.index,monthly_sale.values)
plt.title("Monthly sales Trends ")
plt.xlabel("Month")
plt.ylabel("Total sales")
plt.show()
category_sales=data.groupby('category')['sales'].sum()
plt.figure()
plt.bar(category_sales.index,category_sales.values)
plt.title("Sales by category")
plt.xlabel('Category')
plt.ylabel('total Sales')
plt.show()
product_sales=data.groupby('product')['sales'].sum()
plt.figure()
plt.pie(product_sales.values,labels=product_sales.index,autopct='%1.1f%%')
plt.title("Product Sales Contribution")
plt.show()